stages:
  data_prep:
    cmd: python scripts/models/compute_weights.py en,cs,de,fi,ru,tr,zh
    deps:
      - scripts/models/compute_weights.py
    outs:
      - results/weight_stores/weight_store.en.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.cs.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.de.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.fi.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.ru.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.tr.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.zh.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.en.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.cs.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.de.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.fi.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.ru.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.tr.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.zh.wmt17.bert-base-multilingual-cased.pickle

  test:
    cmd: python scripts/models/performance_test.py en,cs,de,fi,ru,tr,zh wmt18
    deps:
      - src/models/model.py
      - scripts/models/performance_test.py
      - data/raw/wmt18/2018-da.csv
      - results/weight_stores/weight_store.en.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.cs.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.de.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.fi.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.ru.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.tr.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.zh.wmt17.roberta-large-mnli.pickle
      - results/weight_stores/weight_store.en.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.cs.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.de.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.fi.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.ru.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.tr.wmt17.bert-base-multilingual-cased.pickle
      - results/weight_stores/weight_store.zh.wmt17.bert-base-multilingual-cased.pickle
    params:
      - model.distance
      - model.weight_dist
      - model.temporal_type
      - model.reg1
      - model.reg2
      - model.nit
    outs:
      - results/wmt18/correlations/scores.cs-en.json
      - results/wmt18/correlations/scores.de-en.json
      - results/wmt18/correlations/scores.fi-en.json
      - results/wmt18/correlations/scores.ru-en.json
      - results/wmt18/correlations/scores.tr-en.json
      - results/wmt18/correlations/scores.zh-en.json
      - results/wmt18/correlations/scores.en-cs.json
      - results/wmt18/correlations/scores.en-de.json
      - results/wmt18/correlations/scores.en-fi.json
      - results/wmt18/correlations/scores.en-ru.json
      - results/wmt18/correlations/scores.en-tr.json
      - results/wmt18/correlations/scores.en-zh.json

  evaluate:
    cmd: python scripts/models/performance_eval.py wmt18
    deps:
      - scripts/models/performance_eval.py
      - results/wmt18/correlations/scores.cs-en.json
      - results/wmt18/correlations/scores.de-en.json
      - results/wmt18/correlations/scores.fi-en.json
      - results/wmt18/correlations/scores.ru-en.json
      - results/wmt18/correlations/scores.tr-en.json
      - results/wmt18/correlations/scores.zh-en.json
      - results/wmt18/correlations/scores.en-cs.json
      - results/wmt18/correlations/scores.en-de.json
      - results/wmt18/correlations/scores.en-fi.json
      - results/wmt18/correlations/scores.en-ru.json
      - results/wmt18/correlations/scores.en-tr.json
      - results/wmt18/correlations/scores.en-zh.json
    metrics:
      - results/wmt18/correlations/scores/eval.wmt18.cs-en.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.de-en.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.fi-en.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.ru-en.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.tr-en.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.zh-en.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.en-cs.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.en-de.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.en-fi.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.en-ru.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.en-tr.json:
          cache: false
      - results/wmt18/correlations/scores/eval.wmt18.en-zh.json:
          cache: false
